server:
  port: 8080

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb2
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

#Config client configuraction
  #config:
    #import: optional:configserver:http://localhost:8085
  config:
    import: configserver:http://localhost:8085


  #cloud:
   # config:
    #  uri: http://localhost:8085
     # profile: dev
      # label: main
     # fail-fast: true


#Eureka client configuraction
#eureka:
  #client:
    #register-with-eureka: true
    #fetch-registry: true
    #service-url:
      #defaultZone: http://localhost:8761/eureka/