
server:
  port: 8081

spring:
  application:
    name: RATING-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/ratingservicedb2
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

#Config clients configuractions
  config:
    import: optional:configserver:http://localhost:8085


#Eureka Client Configuraction
#eureka:
  #client:
    #register-with-eureka: true
    #fetch-registry: true
    #service-url:
      #defaultZone: http://localhost:8761/eureka